package loungy:command;

interface host {
    use shared.{metadata,callback,app-data,path,state-item};

    state-push: func(item: state-item);
    state-replace: func(item: state-item);
    state-pop: func();
    state-reset: func();

    is-open: func() -> bool;
    open: func();
    toggle: func();
    close: func();
    get-commands: func() -> list<metadata>;
    get-app-data: func(path: path) -> option<app-data>;
    run-command: func(name: string);
    // get-app-folders: func() -> list<path>;
    // get-app-files: func() -> list<path>;
    // get-frontmost-app: func() -> option<app-data>;
    // close-and-paste: func(text: string, format: bool);
    // close-and-paste-file: func(path: path);
    // autofill: func(text: string, password: bool, prev: string) -> option<string>;
    // ocr: func(path: path);
    // wait-for-close: func(callback: func());
    // on-clipboard-change: func(callback: func());
}
