package loungy:command;

interface icons {
  enum icon {
    %hand-helping,
    %underline,
    %file-plus-wit2,
    %sigma,
    %clock-wit9,
    %arrow-right-square,
    %triangle,
    %hand,
    %search,
    %signpost-big,
    %volume-wit2,
    %power-circle,
    %hand-heart,
    %bar-chart-big,
    %contact,
    %send-horizontal,
    %move-down,
    %clipboard-plus,
    %parking-circle-off,
    %gamepad-wit2,
    %lasso,
    %eraser,
    %arrow-up-circle,
    %disc-wit2,
    %receipt,
    %bed-single,
    %wine,
    %pause-circle,
    %parking-meter,
    %check-square,
    %file-search,
    %arrow-down,
    %figma,
    %corner-right-up,
    %file-key,
    %chevrons-right,
    %beef,
    %flashlight,
    %file-pen,
    %ghost,
    %list,
    %cctv,
    %text-cursor-input,
    %globe-wit2,
    %megaphone,
    %croissant,
    %toy-brick,
    %parking-square,
    %route-off,
    %message-circle-question,
    %swiss-franc,
    %navigation-wit2-off,
    %bluetooth-off,
    %bed,
    %panel-right-close,
    %signal-low,
    %chevrons-down,
    %memory-stick,
    %disc-wit3,
    %wind,
    %corner-up-right,
    %clapperboard,
    %subscript,
    %file-digit,
    %arrow-big-down-dash,
    %grape,
    %flip-vertical,
    %hdmi-port,
    %target,
    %user-cog,
    %scissors,
    %minimize-wit2,
    %cog,
    %waypoints,
    %play-circle,
    %megaphone-off,
    %receipt-pound-sterling,
    %crosshair,
    %align-vertical-distribute-end,
    %pi,
    %file-sliders,
    %package-open,
    %vegan,
    %airplay,
    %gallery-thumbnails,
    %clock-wit8,
    %message-circle-warning,
    %badge-euro,
    %x-octagon,
    %repeat,
    %circle-user-round,
    %library-square,
    %arrow-right-left,
    %grip,
    %luggage,
    %hourglass,
    %file-bar-chart,
    %russian-ruble,
    %microwave,
    %volume-wit1,
    %party-popper,
    %boxes,
    %file-heart,
    %reply,
    %badge-percent,
    %sunrise,
    %function-square,
    %toggle-right,
    %bug-off,
    %message-square-share,
    %beer,
    %pointer,
    %receipt-indian-rupee,
    %sheet,
    %spray-can,
    %scan-line,
    %unfold-vertical,
    %git-pull-request-draft,
    %layout-list,
    %umbrella,
    %user,
    %list-start,
    %scatter-chart,
    %lasso-select,
    %arrow-big-down,
    %iteration-cw,
    %fullscreen,
    %message-circle-heart,
    %sun-dim,
    %replace-all,
    %split-square-horizontal,
    %iteration-ccw,
    %message-circle-more,
    %file-minus,
    %x-circle,
    %align-horizontal-justify-start,
    %copy-plus,
    %test-tube-wit2,
    %timer-off,
    %folder-check,
    %badge-japanese-yen,
    %arrow-up-from-line,
    %flip-vertical-wit2,
    %annoyed,
    %ligature,
    %message-square-warning,
    %layout-grid,
    %rocking-chair,
    %chevron-up-square,
    %chevrons-up-down,
    %badge-minus,
    %calendar-off,
    %circle,
    %air-vent,
    %phone-missed,
    %scale-wit3d,
    %corner-left-up,
    %milk,
    %clipboard-pen,
    %home,
    %file-up,
    %copyright,
    %wallet-wit2,
    %picture-in-picture,
    %vault,
    %mailbox,
    %gitlab,
    %music,
    %file-bar-chart-wit2,
    %smartphone,
    %more-horizontal,
    %file-symlink,
    %alarm-clock-check,
    %candy-off,
    %sliders,
    %circuit-board,
    %folder-tree,
    %equal,
    %pause-octagon,
    %recycle,
    %arrow-up-left,
    %clipboard-type,
    %library,
    %panel-top-close,
    %file-pie-chart,
    %list-plus,
    %chevron-down,
    %backpack,
    %calendar-check-wit2,
    %chevron-right-square,
    %heading,
    %hexagon,
    %strikethrough,
    %calendar-fold,
    %message-square-heart,
    %bird,
    %sun-medium,
    %badge-info,
    %shield-plus,
    %book-marked,
    %creative-commons,
    %shirt,
    %signpost,
    %door-closed,
    %github,
    %fold-horizontal,
    %nfc,
    %clipboard-paste,
    %cone,
    %cooking-pot,
    %bring-to-front,
    %usb,
    %separator-vertical,
    %box-select,
    %hard-hat,
    %cake-slice,
    %sun-moon,
    %ticket,
    %calendar-plus-wit2,
    %sigma-square,
    %case-lower,
    %arrow-up-right-from-circle,
    %layout-template,
    %panel-right-open,
    %brackets,
    %star-off,
    %shrink,
    %church,
    %crop,
    %flask-round,
    %cookie,
    %redo-wit2,
    %circle-slash-wit2,
    %tag,
    %book-check,
    %laptop-wit2,
    %cup-soda,
    %option,
    %sparkle,
    %briefcase,
    %presentation,
    %rotate-cw,
    %file-audio,
    %badge-plus,
    %screen-share-off,
    %align-horizontal-distribute-end,
    %file-clock,
    %calendar-search,
    %image-down,
    %swatch-book,
    %radius,
    %folder-sync,
    %panels-top-left,
    %headset,
    %circle-equal,
    %dessert,
    %carrot,
    %receipt-euro,
    %map,
    %check-check,
    %inbox,
    %arrow-up-right-square,
    %align-justify,
    %plus-square,
    %power,
    %a-large-small,
    %tent-tree,
    %database,
    %martini,
    %arrow-up-to-line,
    %monitor-down,
    %badge-indian-rupee,
    %camera-off,
    %fuel,
    %satellite-dish,
    %bike,
    %swords,
    %message-square-off,
    %scan-text,
    %arrow-down-z-a,
    %rat,
    %tornado,
    %contact-wit2,
    %toggle-left,
    %file,
    %puzzle,
    %align-vertical-distribute-center,
    %signal,
    %egg-off,
    %arrow-up-wit1-wit0,
    %file-audio-wit2,
    %baseline,
    %vibrate-off,
    %glass-water,
    %brain,
    %files,
    %torus,
    %scan-search,
    %square-dashed-bottom-code,
    %subtitles,
    %message-circle,
    %message-square-dot,
    %receipt-japanese-yen,
    %voicemail,
    %messages-square,
    %ship-wheel,
    %gantt-chart-square,
    %message-square-quote,
    %contrast,
    %cuboid,
    %alarm-clock-plus,
    %monitor-pause,
    %file-video-wit2,
    %archive-x,
    %terminal,
    %move-diagonal,
    %file-scan,
    %arrow-up-wide-narrow,
    %move,
    %maximize,
    %between-vertical-start,
    %radar,
    %sparkles,
    %lock-keyhole,
    %folder-root,
    %chevron-up,
    %haze,
    %folder-output,
    %folder-symlink,
    %file-badge-wit2,
    %vibrate,
    %laugh,
    %scan-eye,
    %spade,
    %cloud-rain-wind,
    %undo-wit2,
    %file-video,
    %step-back,
    %flask-conical-off,
    %arrow-down-left,
    %file-text,
    %file-stack,
    %folder-open,
    %package-minus,
    %droplet,
    %whole-word,
    %paint-roller,
    %zap-off,
    %keyboard,
    %x,
    %chevrons-right-left,
    %joystick,
    %cigarette,
    %bath,
    %bar-chart,
    %qr-code,
    %dot,
    %languages,
    %ampersands,
    %arrow-left-from-line,
    %bell-minus,
    %file-cog,
    %wheat,
    %chevron-left-circle,
    %cable-car,
    %arrow-up-narrow-wide,
    %lock,
    %dice-wit2,
    %log-in,
    %squircle,
    %shield-ellipsis,
    %ban,
    %smartphone-nfc,
    %list-video,
    %text-select,
    %shopping-bag,
    %divide,
    %piggy-bank,
    %battery-warning,
    %circle-dollar-sign,
    %milk-off,
    %refresh-ccw-dot,
    %tally-wit2,
    %shell,
    %repeat-wit2,
    %pilcrow,
    %circle-dot-dashed,
    %mail-question,
    %cloud-drizzle,
    %copy-minus,
    %spline,
    %refresh-cw,
    %check-square-wit2,
    %pen,
    %plane,
    %code-wit2,
    %align-vertical-space-between,
    %chevron-right,
    %tally-wit3,
    %clipboard,
    %equal-not,
    %asterisk-square,
    %package,
    %instagram,
    %mail-warning,
    %euro,
    %link,
    %dice-wit3,
    %hand-platter,
    %video-off,
    %user-round-plus,
    %key,
    %shrub,
    %sailboat,
    %file-x-wit2,
    %brain-cog,
    %meh,
    %sliders-horizontal,
    %door-open,
    %corner-down-right,
    %beaker,
    %list-todo,
    %cloud-sun,
    %arrow-right,
    %store,
    %antenna,
    %chevron-first,
    %wheat-off,
    %aperture,
    %calendar-plus,
    %brush,
    %thermometer-snowflake,
    %clover,
    %stop-circle,
    %concierge-bell,
    %log-out,
    %unfold-horizontal,
    %file-spreadsheet,
    %file-code-wit2,
    %arrow-left-circle,
    %ship,
    %m-square,
    %ear-off,
    %wallpaper,
    %ambulance,
    %space,
    %file-input,
    %bar-chart-wit2,
    %book-dashed,
    %stretch-vertical,
    %calendar-check,
    %diff,
    %shower-head,
    %square-pen,
    %arrow-down-up,
    %git-pull-request,
    %minimize,
    %group,
    %minus-square,
    %settings,
    %cloud-snow,
    %notepad-text-dashed,
    %calendar-x-wit2,
    %cassette-tape,
    %thumbs-down,
    %dice-wit1,
    %move-down-left,
    %vote,
    %type,
    %mouse-pointer-click,
    %regex,
    %popsicle,
    %lamp-floor,
    %utensils,
    %archive,
    %bean,
    %panels-right-bottom,
    %message-square-text,
    %refresh-cw-off,
    %phone-outgoing,
    %arrow-up-left-square,
    %tally-wit1,
    %arrow-up-from-dot,
    %candy,
    %pocket,
    %repeat-wit1,
    %magnet,
    %mail,
    %school,
    %arrow-big-right,
    %shield,
    %download,
    %kanban,
    %file-volume,
    %expand,
    %gallery-vertical-end,
    %file-warning,
    %disc-album,
    %pin,
    %arrow-up-a-z,
    %bar-chart-horizontal-big,
    %import,
    %webcam,
    %phone-forwarded,
    %bell-plus,
    %corner-right-down,
    %book-open,
    %forklift,
    %divide-square,
    %castle,
    %area-chart,
    %orbit,
    %parentheses,
    %projector,
    %server,
    %user-round-check,
    %bolt,
    %tv,
    %message-square-dashed,
    %droplets,
    %skip-forward,
    %archive-restore,
    %volume,
    %lamp-wall-up,
    %bar-chart-wit3,
    %drumstick,
    %user-plus,
    %battery-medium,
    %book-a,
    %arrow-down-left-from-square,
    %chevron-down-square,
    %battery-charging,
    %shapes,
    %folders,
    %satellite,
    %activity-square,
    %list-minus,
    %indent,
    %bookmark-minus,
    %heater,
    %layers,
    %dna,
    %file-check-wit2,
    %slash,
    %radio,
    %align-center-vertical,
    %alarm-clock,
    %alarm-clock-off,
    %book,
    %keyboard-music,
    %hotel,
    %book-text,
    %variable,
    %touchpad-off,
    %bitcoin,
    %message-square-x,
    %car-front,
    %alarm-smoke,
    %dice-wit4,
    %skull,
    %mail-minus,
    %bot,
    %plug,
    %shield-x,
    %train-track,
    %goal,
    %gauge-circle,
    %folder-archive,
    %signal-high,
    %user-minus,
    %plane-landing,
    %wallet,
    %tally-wit4,
    %file-image,
    %square-dashed-bottom,
    %menu-square,
    %panel-top-open,
    %bell,
    %git-branch,
    %coffee,
    %panel-left-dashed,
    %code,
    %rail-symbol,
    %cake,
    %spell-check-wit2,
    %settings-wit2,
    %tally-wit5,
    %message-circle-dashed,
    %cloud-moon-rain,
    %radio-tower,
    %thermometer,
    %cast,
    %milestone,
    %move-wit3d,
    %flag,
    %podcast,
    %pi-square,
    %git-fork,
    %eye-off,
    %dice-wit5,
    %tram-front,
    %battery,
    %split-square-vertical,
    %arrow-down-square,
    %blinds,
    %arrow-left-to-line,
    %newspaper,
    %arrow-up-left-from-square,
    %clipboard-pen-line,
    %snowflake,
    %disc,
    %step-forward,
    %bomb,
    %piano,
    %book-copy,
    %arrow-up-wit0-wit1,
    %database-zap,
    %rotate-wit3d,
    %star-half,
    %switch-camera,
    %image-plus,
    %pencil-ruler,
    %container,
    %ruler,
    %turtle,
    %frown,
    %tree-pine,
    %audio-lines,
    %circle-slash,
    %outdent,
    %notebook-text,
    %layout-dashboard,
    %file-line-chart,
    %cpu,
    %align-end-horizontal,
    %flame-kindling,
    %clipboard-list,
    %biohazard,
    %bar-chart-wit4,
    %folder-x,
    %book-open-check,
    %list-ordered,
    %factory,
    %bold,
    %arrow-down-right-from-circle,
    %tablets,
    %fence,
    %trophy,
    %hash,
    %shield-minus,
    %link-wit2-off,
    %share-wit2,
    %battery-full,
    %plus,
    %paintbrush-wit2,
    %monitor-stop,
    %panel-bottom,
    %clipboard-minus,
    %check,
    %percent-square,
    %align-vertical-justify-end,
    %rabbit,
    %plug-zap,
    %nut,
    %mail-plus,
    %move-down-right,
    %rotate-ccw,
    %heart-crack,
    %flip-horizontal-wit2,
    %hard-drive,
    %between-horizontal-end,
    %tent,
    %ice-cream-wit2,
    %hard-drive-download,
    %circle-fading-plus,
    %pen-line,
    %align-vertical-space-around,
    %case-sensitive,
    %focus,
    %bluetooth,
    %align-end-vertical,
    %pie-chart,
    %headphones,
    %table-properties,
    %git-pull-request-create-arrow,
    %folder-git-wit2,
    %rss,
    %flower-wit2,
    %landmark,
    %wifi,
    %corner-up-left,
    %file-archive,
    %arrow-down-from-line,
    %watch,
    %scale,
    %dice-wit6,
    %message-square-more,
    %ampersand,
    %dna-off,
    %hand-coins,
    %roller-coaster,
    %monitor-smartphone,
    %git-commit-vertical,
    %info,
    %blocks,
    %popcorn,
    %file-badge,
    %badge-dollar-sign,
    %user-x,
    %navigation-off,
    %key-square,
    %ticket-minus,
    %dog,
    %layout-panel-left,
    %fan,
    %radio-receiver,
    %loader,
    %palette,
    %receipt-swiss-franc,
    %package-wit2,
    %case-upper,
    %parking-circle,
    %refresh-ccw,
    %cloud-fog,
    %percent-diamond,
    %git-branch-plus,
    %file-x,
    %heading-wit1,
    %hop,
    %folder-up,
    %soup,
    %folder-plus,
    %badge-russian-ruble,
    %git-merge,
    %japanese-yen,
    %grip-horizontal,
    %list-x,
    %shield-half,
    %mic,
    %venetian-mask,
    %rainbow,
    %git-pull-request-arrow,
    %copy,
    %smile-plus,
    %fish,
    %move-up-left,
    %list-tree,
    %zoom-in,
    %search-check,
    %play-square,
    %arrow-down-to-line,
    %glasses,
    %coins,
    %align-start-vertical,
    %arrows-up-from-line,
    %snail,
    %library-big,
    %bookmark-x,
    %book-key,
    %panel-left,
    %unlock-keyhole,
    %message-circle-off,
    %square-user-round,
    %file-type-wit2,
    %text-quote,
    %caravan,
    %badge-cent,
    %panel-top-dashed,
    %notebook-tabs,
    %arrow-right-circle,
    %text,
    %test-tubes,
    %fire-extinguisher,
    %egg-fried,
    %flag-triangle-left,
    %power-square,
    %align-right,
    %text-cursor,
    %image,
    %panel-bottom-open,
    %maximize-wit2,
    %lightbulb,
    %server-off,
    %check-circle,
    %arrow-big-left-dash,
    %sunset,
    %save,
    %smile,
    %search-code,
    %arrow-up-square,
    %lamp,
    %siren,
    %scan,
    %navigation,
    %cloud-lightning,
    %citrus,
    %message-square-diff,
    %bell-electric,
    %candlestick-chart,
    %monitor-play,
    %badge-pound-sterling,
    %hard-drive-upload,
    %app-window,
    %badge,
    %theater,
    %paperclip,
    %heading-wit2,
    %fast-forward,
    %x-square,
    %flag-triangle-right,
    %calendar-range,
    %syringe,
    %search-slash,
    %file-question,
    %bar-chart-horizontal,
    %sticker,
    %award,
    %panel-right-dashed,
    %zoom-out,
    %box,
    %thumbs-up,
    %superscript,
    %ticket-percent,
    %battery-low,
    %touchpad,
    %speech,
    %pilcrow-square,
    %percent,
    %square,
    %crown,
    %bluetooth-searching,
    %timer-reset,
    %chevron-up-circle,
    %stethoscope,
    %eclipse,
    %donut,
    %candy-cane,
    %play,
    %folder-heart,
    %file-check,
    %leafy-green,
    %tangent,
    %book-audio,
    %table,
    %split,
    %send,
    %barcode,
    %videotape,
    %scissors-square,
    %dot-square,
    %scroll,
    %phone-call,
    %columns-wit4,
    %baggage-claim,
    %radiation,
    %speaker,
    %user-round-search,
    %undo-dot,
    %facebook,
    %codesandbox,
    %file-down,
    %badge-check,
    %arrow-down-right-square,
    %baby,
    %smartphone-charging,
    %book-plus,
    %unplug,
    %heading-wit3,
    %bluetooth-connected,
    %camera,
    %link-wit2,
    %printer,
    %list-collapse,
    %workflow,
    %trees,
    %panel-left-close,
    %git-graph,
    %redo,
    %club,
    %folder-minus,
    %move-diagonal-wit2,
    %combine,
    %arrow-up-right,
    %truck,
    %layout-panel-top,
    %life-buoy,
    %user-search,
    %square-user,
    %between-horizontal-start,
    %package-x,
    %pen-tool,
    %alarm-clock-minus,
    %panels-left-bottom,
    %folder-cog,
    %at-sign,
    %arrow-up-right-from-square,
    %shield-alert,
    %map-pin-off,
    %list-restart,
    %hand-metal,
    %egg,
    %car-taxi-front,
    %monitor-x,
    %bus,
    %file-pen-line,
    %book-heart,
    %infinity,
    %gem,
    %filter-x,
    %git-compare,
    %receipt-cent,
    %feather,
    %webhook-off,
    %trash,
    %arrow-down-wit1-wit0,
    %database-backup,
    %armchair,
    %wifi-off,
    %user-round,
    %ungroup,
    %school-wit2,
    %book-lock,
    %leaf,
    %arrow-down-wide-narrow,
    %network,
    %file-lock-wit2,
    %arrow-up-z-a,
    %scan-barcode,
    %corner-left-down,
    %message-square-plus,
    %equal-square,
    %folder-clock,
    %dollar-sign,
    %triangle-right,
    %indian-rupee,
    %mic-wit2,
    %construction,
    %graduation-cap,
    %scan-face,
    %fish-symbol,
    %monitor-speaker,
    %guitar,
    %chevron-right-circle,
    %star,
    %monitor-check,
    %sandwich,
    %chef-hat,
    %heading-wit6,
    %cloud-off,
    %save-all,
    %sun,
    %wrench,
    %signal-medium,
    %grab,
    %pyramid,
    %book-minus,
    %gauge,
    %message-square,
    %bug-play,
    %book-x,
    %loader-wit2,
    %heading-wit4,
    %pizza,
    %unlink,
    %chevrons-down-up,
    %bone,
    %flashlight-off,
    %file-json-wit2,
    %anchor,
    %hammer,
    %alert-circle,
    %plug-wit2,
    %notebook-pen,
    %chevrons-up,
    %columns-wit3,
    %move-horizontal,
    %highlighter,
    %tablet-smartphone,
    %upload-cloud,
    %twitch,
    %banana,
    %tree-deciduous,
    %folder-lock,
    %locate,
    %list-music,
    %bug,
    %panel-top,
    %message-square-code,
    %mail-open,
    %youtube,
    %chevrons-left-right,
    %bookmark-plus,
    %a-arrow-up,
    %unlock,
    %tower-control,
    %book-up,
    %pocket-knife,
    %shovel,
    %compass,
    %file-minus-wit2,
    %kanban-square,
    %align-horizontal-justify-end,
    %plus-circle,
    %server-crash,
    %traffic-cone,
    %plane-takeoff,
    %folder-kanban,
    %mail-search,
    %cloud-moon,
    %columns-wit2,
    %warehouse,
    %frame,
    %credit-card,
    %table-wit2,
    %file-key-wit2,
    %copyleft,
    %grid-wit3x3,
    %tv-wit2,
    %ticket-x,
    %align-vertical-justify-start,
    %heart-off,
    %cylinder,
    %computer,
    %book-type,
    %parking-square-off,
    %heading-wit5,
    %thermometer-sun,
    %terminal-square,
    %badge-help,
    %locate-off,
    %reply-all,
    %pencil,
    %cloud-rain,
    %send-to-back,
    %kanban-square-dashed,
    %git-pull-request-closed,
    %arrow-big-right-dash,
    %align-vertical-distribute-start,
    %book-down,
    %pound-sterling,
    %monitor-up,
    %bean-off,
    %trash-wit2,
    %circle-user,
    %skip-back,
    %file-plus,
    %scroll-text,
    %gantt-chart,
    %diamond,
    %delete,
    %command,
    %package-check,
    %align-center-horizontal,
    %clock,
    %bell-ring,
    %remove-formatting,
    %router,
    %footprints,
    %octagon,
    %arrow-big-left,
    %phone,
    %arrow-down-left-square,
    %land-plot,
    %align-horizontal-justify-center,
    %sun-snow,
    %image-off,
    %umbrella-off,
    %arrow-down-a-z,
    %panel-left-open,
    %brain-circuit,
    %move-vertical,
    %users-round,
    %salad,
    %dumbbell,
    %arrow-left-square,
    %tractor,
    %waves,
    %folder-closed,
    %eye,
    %user-round-cog,
    %badge-alert,
    %server-cog,
    %pipette,
    %phone-off,
    %flower,
    %banknote,
    %sprout,
    %brick-wall,
    %copy-check,
    %rectangle-vertical,
    %pill,
    %chevron-left-square,
    %codepen,
    %dribbble,
    %message-circle-plus,
    %axe,
    %gift,
    %receipt-russian-ruble,
    %package-plus,
    %external-link,
    %line-chart,
    %currency,
    %wand,
    %file-music,
    %car,
    %zap,
    %trello,
    %list-checks,
    %more-vertical,
    %message-square-reply,
    %badge-x,
    %building-wit2,
    %moon-star,
    %clock-wit1,
    %cigarette-off,
    %binary,
    %chevron-last,
    %pointer-off,
    %mouse-pointer-wit2,
    %package-search,
    %mic-off,
    %lamp-desk,
    %share,
    %tags,
    %album,
    %key-round,
    %folder-search-wit2,
    %arrow-up,
    %microscope,
    %test-tube,
    %bell-off,
    %linkedin,
    %arrow-down-narrow-wide,
    %clock-wit3,
    %panel-right,
    %drum,
    %view,
    %music-wit2,
    %wrap-text,
    %git-compare-arrows,
    %calendar-minus,
    %book-image,
    %file-volume-wit2,
    %slash-square,
    %user-round-x,
    %undo,
    %video,
    %circle-ellipsis,
    %divide-circle,
    %activity,
    %pencil-line,
    %person-standing,
    %twitter,
    %map-pin,
    %folder-input,
    %filter,
    %lightbulb-off,
    %phone-incoming,
    %refrigerator,
    %italic,
    %list-end,
    %handshake,
    %chevrons-left,
    %rows-wit2,
    %mail-x,
    %medal,
    %message-circle-code,
    %calendar,
    %inspection-panel,
    %notepad-text,
    %message-circle-x,
    %arrow-right-from-line,
    %globe,
    %arrow-left,
    %paintbrush,
    %rows-wit3,
    %align-center,
    %badge-swiss-franc,
    %cross,
    %route,
    %diameter,
    %pc-case,
    %calendar-heart,
    %minus-circle,
    %book-headphones,
    %arrow-down-right,
    %file-box,
    %paw-print,
    %laptop,
    %power-off,
    %redo-dot,
    %axis-wit3d,
    %arrow-big-up,
    %framer,
    %mountain,
    %stretch-horizontal,
    %bell-dot,
    %clipboard-x,
    %folder-down,
    %shield-question,
    %panel-bottom-dashed,
    %volume-x,
    %music-wit3,
    %copy-slash,
    %file-code,
    %move-left,
    %slack,
    %circle-dashed,
    %clock-wit2,
    %user-round-minus,
    %scissors-line-dashed,
    %file-output,
    %cloud,
    %hop-off,
    %download-cloud,
    %clock-wit11,
    %shuffle,
    %quote,
    %anvil,
    %washing-machine,
    %grip-vertical,
    %clock-wit6,
    %drill,
    %form-input,
    %plug-zap-wit2,
    %align-horizontal-distribute-start,
    %file-type,
    %rewind,
    %wine-off,
    %upload,
    %trending-down,
    %bookmark-check,
    %fold-vertical,
    %calendar-x,
    %pause,
    %arrow-big-up-dash,
    %folder-key,
    %grid-wit2x2,
    %arrow-down-circle,
    %cloud-hail,
    %search-x,
    %cloudy,
    %replace,
    %forward,
    %mountain-snow,
    %wand-wit2,
    %dices,
    %blend,
    %bookmark,
    %arrow-up-left-from-circle,
    %alert-triangle,
    %braces,
    %rocket,
    %circle-dot,
    %move-right,
    %drama,
    %palmtree,
    %asterisk,
    %user-check,
    %calendar-clock,
    %fish-off,
    %folder-search,
    %folder-pen,
    %cloud-sun-rain,
    %git-pull-request-create,
    %tablet,
    %mail-check,
    %align-vertical-justify-center,
    %file-diff,
    %monitor-dot,
    %ticket-slash,
    %align-horizontal-space-between,
    %webhook,
    %alert-octagon,
    %folder-open-dot,
    %arrow-down-left-from-circle,
    %arrow-left-right,
    %chevron-down-circle,
    %utility-pole,
    %signal-zero,
    %book-up-wit2,
    %monitor-off,
    %ear,
    %spell-check,
    %file-terminal,
    %flame,
    %gallery-horizontal-end,
    %nut-off,
    %component,
    %circle-off,
    %file-search-wit2,
    %align-start-horizontal,
    %locate-fixed,
    %atom,
    %cat,
    %cloud-cog,
    %sword,
    %ice-cream,
    %squirrel,
    %menu,
    %pin-off,
    %lamp-ceiling,
    %folder-dot,
    %scissors-square-dashed-bottom,
    %utensils-crossed,
    %ratio,
    %gallery-vertical,
    %image-minus,
    %clock-wit7,
    %arrow-right-to-line,
    %a-arrow-down,
    %merge,
    %map-pinned,
    %align-horizontal-space-around,
    %chrome,
    %sticky-note,
    %ticket-plus,
    %shopping-cart,
    %copy-x,
    %calculator,
    %clock-wit10,
    %train-front-tunnel,
    %clock-wit12,
    %apple,
    %mouse,
    %flask-conical,
    %picture-in-picture-wit2,
    %pentagon,
    %shield-check,
    %arrow-down-wit0-wit1,
    %message-circle-reply,
    %mails,
    %clock-wit5,
    %rectangle-horizontal,
    %shopping-basket,
    %list-filter,
    %receipt-text,
    %music-wit4,
    %book-user,
    %shield-ban,
    %arrow-down-to-dot,
    %building,
    %clipboard-copy,
    %angry,
    %check-circle-wit2,
    %lollipop,
    %between-vertical-end,
    %history,
    %gavel,
    %folder,
    %drafting-compass,
    %align-horizontal-distribute-center,
    %file-lock,
    %layers-wit2,
    %code-square,
    %users,
    %boom-box,
    %slice,
    %folder-git,
    %fingerprint,
    %flag-off,
    %corner-down-left,
    %mouse-pointer-square,
    %file-axis-wit3d,
    %book-open-text,
    %timer,
    %gamepad,
    %git-commit-horizontal,
    %monitor,
    %clipboard-check,
    %unlink-wit2,
    %minus,
    %heart-pulse,
    %rows-wit4,
    %heart-handshake,
    %bed-double,
    %text-search,
    %help-circle,
    %audio-waveform,
    %navigation-wit2,
    %paint-bucket,
    %chevron-left,
    %move-up,
    %film,
    %moon,
    %panel-bottom-close,
    %weight,
    %shield-off,
    %layers-wit3,
    %scaling,
    %arrow-down-right-from-square,
    %cable,
    %accessibility,
    %move-up-right,
    %wallet-cards,
    %percent-circle,
    %bus-front,
    %lamp-wall-down,
    %mouse-pointer,
    %file-json,
    %train-front,
    %calendar-minus-wit2,
    %ribbon,
    %square-stack,
    %flip-horizontal,
    %gallery-horizontal,
    %notebook,
    %stamp,
    %arrow-up-down,
    %screen-share,
    %calendar-days,
    %align-left,
    %separator-horizontal,
    %ferris-wheel,
    %sofa,
    %clock-wit4,
    %ticket-check,
    %cherry,
    %heart,
    %trending-up,
    %mouse-pointer-square-dashed,
  }
}
