package loungy:command;

interface shared {
  use icons.{icon};

  type color = string;

  record icon-colored {
      icon: icon,
      color: option<color>,
  }
  variant img-source {
      uri(string),
      path(string),
      dot(color),
      favicon(string),
      icon(icon-colored),
      none,
  }

  record modifiers {
      platform: bool,
      shift: bool,
      ctrl: bool,
      alt: bool,
  }

  record shortcut {
      key: string,
      modifiers: modifiers,
  }

  record action {
      label: string,
      image: img,
      shortcut: option<shortcut>,
      callback: callback,
      hide: bool,
  }

  variant img-mask {
      circle,
      rounded,
      none,
  }
  variant img-size {
      xs,
      sm,
      md,
      lg,
  }
  variant object-fit {
      contain,
      cover,
      fill,
      none,
  }
  record img {
      mask: img-mask,
      source: img-source,
      size: img-size,
      object-fit: object-fit,
  }
  record app-data {
      id: string,
      name: string,
      icon: img,
      icon-path: path,
      keywords: list<string>,
      tag: string,
  }

  type path = string;
  type callback = string;
  variant callback-payload {
    filter(string),
    none,
  }
  variant callback-result {
    %list(list-item),
    none,
  }
  record metadata {
      id: string,
      title: string,
      subtitle: string,
      keywords: list<string>,
      icon: img,
  }

  record list-item-simple {
    title: string,
    subtitle: string,
    img: img,
    accessories: list<accessory>,
  }
  variant list-item-component {
    simple(list-item-simple)
  }
  record accessory-tag {
    tag: string,
    img: img,
  }
  variant accessory {
    tag(accessory-tag),
    shortcut(shortcut),
    none,
  }
  record list-item {
      id: string,
      preview: option<callback>,
      actions: list<action>,
      weight: option<u32>,
      keywords: list<string>,
      meta: list<u8>,
      component: list-item-component,
      update: callback,
      filter: option<callback>,
  }

  record %list {
      items: list<list-item>,
      interval: option<u64>,
  }

  variant state-component {
    %list(%list),
    none,
  }

  record state-item {
    id: string,
    actions: list<action>,
    workspace: bool,
    component: state-component,
  }
}